print("GitHub!")
print ("Hello!")
print ("Hi!")
print ("How are you?")
print ("Hey Hey Hey!")
print ("Hello NEW!")
print ("Hello From another GitHub!")
print ("New branch!")
print ("HI!")
print ("I lov github!")
print ("HEY HEY!")
print ("Hey!")
print ("H")
print ("Mostik")
print( "HEEEEYY")
print ("Love python")
print("Q")
